

### Upload image
POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--MyBoundary--

@imageID = "number given to the image when uploaded goes here"
### Upload image
Get http://localhost:3000/images/imageID HTTP/1.1